# Generated by Django 5.1.1 on 2024-10-28 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussiontopic',
            options={'ordering': ['-pinned', '-last_activity']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General Discussion'), ('TECH', 'Technology'), ('SUPPORT', 'Support'), ('OTHER', 'Other')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='max_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
