# Generated by Django 5.1.1 on 2024-10-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_discussiontopic_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussiontopic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='discussiontopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='discussiontopic',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='discussiontopic',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='discussiontopic',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='discussiontopic',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='discussiontopic',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mentioned_users',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
    ]
